# Generated by Django 4.1.2 on 2022-10-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jedzonko', '0002_alter_recipe_name_alter_recipe_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
