# Generated by Django 4.1.2 on 2022-10-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0004_dayname_recipeplan_plan_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeplan',
            name='meal_name',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
