# Generated by Django 4.1.2 on 2022-10-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0005_recipeplan_meal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
