# Generated by Django 4.1.2 on 2022-12-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0007_alter_plan_created_alter_recipe_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeplan',
            name='order',
        ),
    ]
