# Generated by Django 4.1.2 on 2022-12-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0008_remove_recipeplan_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeplan',
            name='order',
            field=models.PositiveIntegerField(default=2, unique=True),
            preserve_default=False,
        ),
    ]
